import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = new Date()
  return (
    <html lang="en">
      <body className='flex flex-col justify-start gap-4 p-20 items-center min-h-screen'>
        
        <header className="flex flex-col items-center">
          <h1>React & Next.js</h1>
          <nav>
            <ul className="flex gap-2" >
              <li><Link href ="/">Intro</Link></li>
              <li><Link href ="/sobre">Sobre</Link></li>
              <li><Link href = "/projetos">projetos</Link></li>
              <li><Link href = "/orgulho">orgulho</Link></li>
            </ul>
          </nav>
        </header>
        
        <main className="bg-blue-200 p-5 rounded-2xl max-w-2xl min-h-[70vh]">
          {children}
        </main>
        
        <footer>DIW {data.getFullYear()}</footer>

      </body>
    </html>
  );
  /*
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} 
        antialiased h-min-screen flex flex-col justify-center items-center`
      }>
        <header>
        <h1> A minha app </h1>
          <nav>
            <ul className="flex gap-2" >
              <li><Link href ="/">Intro</Link></li>
              <li><Link href ="/sobre">Sobre</Link></li>
              <li><Link href = "/projetos">projetos</Link></li>
              <li><Link href = "/orgulho">orgulho</Link></li>
            </ul>
          </nav>
        </header>
        <main>
          {children}
        </main>
        <footer>
        DIW
        </footer>
      </body>
    </html>
  );
  */
}
